from randomdict import RandomDict

easy_syllables = RandomDict()
for syllable in {
    "ba", "be", "bi", "bo", "bu",
    "da", "de", "di", "do", "du",
    "ma", "me", "mi", "mo", "mu",
    "pa", "pe", "pi", "po", "pu",
    "ra", "re", "ri", "ro", "ru",
    "sa", "se", "si", "so", "su",
    "ta", "te", "ti", "to", "tu",
    "ing", "ed", "er", "ly",
    "ay", "ee", "oo",
    "re", "un", "up",
    "lo", "ja", "zi", "nu", "fe",
    "ki", "ho", "mo", "za", "la",
    "vi", "wa", "ne", "yo", "ha",
    "ca", "ce", "ci", "co", "cu",
    "na", "ni", "no", "nu",
    "ya", "ye", "yi", "yo",
    "al", "an", "en", "in", "on",
    "ex", "im", "es", "et",
    "by", "my", "ty", "ry",
    "fo", "go", "hi", "jo",
    "que", "qui", "ka", "ke"
}:
    easy_syllables[syllable] = None

medium_syllables = RandomDict()
for syllable in {
    "fa", "fe", "fi", "fo", "fu",
    "ga", "ge", "gi", "go", "gu",
    "ha", "he", "hi", "ho", "hu",
    "ja", "je", "ji", "jo", "ju",
    "ka", "ke", "ki", "ko",
    "la", "le", "li", "lo", "lu",
    "na", "ne", "ni", "no", "nu",
    "va", "ve", "vi", "vo", "vu",
    "wa", "we", "wi", "wo",
    "za", "ze", "zi", "zo", "zu",
    "bla", "ble", "blo",
    "cha", "che", "chi",
    "pla", "ple", "plo",
    "sta", "ste", "sto",
    "tra", "tre", "tri",
    "ment", "ness", "able", "ful", "less",
    "age", "ize", "ity", "ous",
    "ai", "ea", "oa", "oi", "ou",
    "dis", "mis", "non", "over", "pre",
    "bra", "bre", "bri", "bro", "bru",
    "dra", "dro", "gru", "swa", "swe",
    "fra", "flo", "sta", "sle", "spi",
    "blo", "cla", "gle", "phy", "sci",
    "tha", "tho", "qua", "qui", "sha",
    "pro", "pre", "pri",
    "spr", "str", "scr",
    "thr", "sch", "shr",
    "able", "ible", "ance",
    "ence", "ling", "tion",
    "kno", "psy", "rhy",
    "syn", "sym", "sys",
    "theo", "tech", "tele",
    "para", "meta", "anti",
    "fore", "back", "down"
}:
    medium_syllables[syllable] = None

hard_syllables = RandomDict()
for syllable in {
    "cra", "cre", "cri", "cro", "cru",
    "dra", "dre", "dri", "dro", "dru",
    "fra", "fre", "fri", "fro", "fru",
    "gra", "gre", "gri", "gro", "gru",
    "ska", "ske", "ski", "sko", "sku",
    "sma", "sme", "smi", "smo", "smu",
    "sna", "sne", "sni", "sno", "snu",
    "tion", "sion", "ible", "ably", "ibly",
    "ial", "ical", "ious", "ive", "ify",
    "anti", "auto", "inter", "semi", "super",
    "trans", "under",
    "phon", "graph", "scope", "sphere", "logy",
    "meter", "gram", "port", "form", "duct",
    "struct", "script", "rupt", "tract", "ject",
    "pose", "tend", "tain", "sist", "spect",
    "plex", "plic", "chron", "morph", "hydr",
    "therm", "astro", "geo", "bio", "psych",
    "mega", "nano", "penta", "hexa", "octo",
    "micro", "macro", "circum", "contra", "ambi",
    "hypo", "hyper", "peri", "mono", "poly",
    "phyll", "zym", "thel", "glyph", "lith",
    "phys", "psych", "pneum",
    "mnem", "xeno", "pseudo",
    "cipher", "sphinx", "rhythm",
    "lymph", "crypt", "synch",
    "quantum", "quark", "quorum",
    "phthis", "schwa", "thresh",
    "archae", "aether", "aegis",
    "gnosis", "pteryx", "sphinx",
    "chloro", "chryso", "pharma",
    "psycho", "physio", "rhetor"
}:
    hard_syllables[syllable] = None